networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - /etc/letsencrypt:/etc/letsencrypt:ro         # Папка с сертификатами
      - ./frontend/dist:/usr/share/nginx/html  # Если фронтенд — статика
    networks:
      - dev
    
    depends_on:
      - backend
      - frontend

  backend:
    build: 
      context: ./backend
      volumes:
        - ./backend/img:/app/backend/img
    networks:
      - dev

  frontend:
    build: 
      context: ./frontend
    networks:
      - dev
