networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "80:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    
    depends_on:
      - backend
      - frontend

  backend:
    build: 
      context: ./backend
    networks:
      - dev

  frontend:
    build: 
      context: ./frontend
      args:
        NODE_OPTIONS: --max_old_space_size=4096
    networks:
      - dev
    deploy:
      resources:
        limits:
          memory: 2G 
          cpus: 1.5
